### ISSUE TITLE
Version 2.0.6 not working on Firefox 55 (64-bit), Linux

### ISSUE THREAD

**Issue by pviotti** [autonome/alwaysright#14]
as per title. :(

anyway, thanks for the extension: very useful. 
(also, wouldn't it make sense to have this as a Firefox setting..?)

**Comment by pviotti** [comment]
to be precise, it works for links opened in new tabs, but it doesn't work for new empty tabs (`Ctrl+t`), which are opened at the end of the list of tabs.

**Comment by autonome** [comment]
Thanks for reporting! I cannot reproduce in Mac or Windows. I'm installing
latest Ubuntu in a VM to test there.

**Comment by autonome** [comment]
Installed Firefox nightly (57) and cannot reproduce the problem. I'm
waiting for Ubuntu updates to see if the version included with Ubuntu
updates to 55, but it's taking a while.

**Comment by Nexion** [comment]
@autonome I [reported](https://github.com/autonome/Always-Right/issues/13#issuecomment-322662565) this problem already, on that moment I had firefox 54.0.1. Currently it's 55.0.1 (x64 Linux) and the problem is still here.

The workaround within the browser session is the same: to disable and re-enable the addon again. But even after that sometimes it still can sporadically open tabs at the very end.

**Comment by grahamperrin** [comment]
Reproducible with 2.0.6 on Firefox 56.0 (64-bit) on FreeBSD. 

[2017-10-01 14:55:17.mp4.tar.gz](https://github.com/autonome/Always-Right/files/1347168/2017-10-01.14.55.17.mp4.tar.gz)

```text
[grahamperrin@momh167-gjp4-hpelitebook8570p-freebsd] ~% uname -v
FreeBSD 12.0-CURRENT #0 r320869: Mon Jul 10 13:57:55 UTC 2017     root@releng3.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC 
[grahamperrin@momh167-gjp4-hpelitebook8570p-freebsd] ~% pkg info firefox | grep -i version
Version        : 56.0,1
[grahamperrin@momh167-gjp4-hpelitebook8570p-freebsd] ~% 
```

I might retest with a less heavily extended profile.

**Comment by grahamperrin** [comment]
> … maybe … an extension conflict …

That's possible, but essentially I reproduced the issue with: 

- Always Right alone; and 
- session restoration of more than nine hundred tabs. 

Two frames from the attached screen recording: 

![2017-10-01 15 27 39 frame](https://user-images.githubusercontent.com/192271/31055805-7929434c-a6c0-11e7-92a9-c58d65da2c01.png)
![2017-10-01 15 27 41 frame](https://user-images.githubusercontent.com/192271/31055806-792ddf74-a6c0-11e7-9823-ab90e0cb4a8e.png)

[2017-10-01 15:26:19.mp4.tar.gz](https://github.com/autonome/Always-Right/files/1347222/2017-10-01.15.26.19.mp4.tar.gz)

Not yet _consistently_ reproducible – sorry – but there's an example of the **first new tab misplaced** (not sliding into place after its first appearance).

**Comment by autonome** [comment]
It looks like you have tree-style tabs installed, so another tab-related
add-on is definitely there in addition to Always Right.

**Comment by grahamperrin** [comment]
> … another tab-related add-on is definitely there …

No, definitely not. Please view the screen recording, it's less than three minutes, here's another frame: 

![2017-10-01 15 26 48 frame](https://user-images.githubusercontent.com/192271/31058091-aa697aba-a6e5-11e7-9c37-d298e778a180.png)

**Comment by autonome** [comment]
Oops, sorry, I thought the bar on the left was tree-style tabs or something like that 😂

I'm looking through the code to see if there's anything where we might have a race, or some invalid activeTab value that could cause this.

**Comment by grahamperrin** [comment]
:-) 

Maybe worth mentioning: whilst there's no Tab Groups installation in the profile that I used to demonstrate the issue, the session file for the demo _did_ originate from an everyday profile where I make extensive use of Tab Groups.

**Comment by autonome** [comment]
The underlying Firefox code and APIs are all different now, and the extension has been updated to manifest v3 so all the code from this period is likely entirely different. We can reopen if you're still having issues.
