### ISSUE TITLE
Always left on close

### ISSUE THREAD

**Issue by szepeviktor** [autonome/alwaysright#2]
Please consider adding the complementing feature:
When closing a tab focus goes to the tab on the left.

**Comment by NEO-SPECTRUMAN** [comment]
+1
always right on close is annoying and totally unnatural

**Comment by szepeviktor** [comment]
@NEO-SPECTRUMAN Have you seen `browser.tabs.insertAfterCurrent`?
browser.tabs.insertAfterCurrent

**Comment by NEO-SPECTRUMAN** [comment]
> browser.tabs.insertAfterCurrent
i set it to true 
but it doesn't help

**Comment by NEO-SPECTRUMAN** [comment]
> @NEO-SPECTRUMAN Have you seen `browser.tabs.insertAfterCurrent` in Firefox? https://support.mozilla.org/en-US/questions/1329071

looks like i mistook it with other software (i'm half year without internet)
now i can't reproduce focus on the right tab... 

browser.tabs.insertAfterCurrent - doesn't works in sequential opening
when you open 1 tab per 10 sec
it opens [current] [tab 3] [tab 2] [tab 1]
when you open 1 tab per 0.2 sec
it opens [current] [tab 1] [tab 2] [tab 3]
or [current] [tab 4] [tab 5] [tab 6] [tab 1] [tab 2] [tab 3]

**Comment by autonome** [comment]
Thanks for requesting. However this is a very narrowly focused extension. Adding this feature would obviate the name. I recommend looking at the source code and making a new extension which has this behavior.
