### ISSUE TITLE
Inconsistent background tab placement

### ISSUE THREAD

**Issue by monk-time** [autonome/alwaysright#20]
By default Firefox always opens links opened from the same tab in background (with a middle click or through a context menu → Open Link in New Tab) next to each other in the order of opening, until the user switches to another tab. So if my current tabs are `[a] b` with `a` active, and I open tabs `1 2 3` in that order, I'll get `[a] 1 2 3 b`. Similarly `a [b]` → `a [b] 1 2 3`. That's the default FF behavior since version 3.6.

Always Right preserves this very convenient behavior (and AFAICT is the only WE of its kind that does so) almost always except when opening links from the last tab :
`[a] b` → `[a] 1 2 3 b`
 `a [b]` → `a [b] 3 2 1`
And this is rather buggy too: `a [b] 3 2 1` is what I get if I open links fast enough, but if any of the opened bg tabs has time to load while I open other tabs, the add-on switches to the default ordering, which is very confusing:
`a [b]` → `a [b] 3 4 5 2 1`.

Here's how it looks:

![2017-11-20_18-32-32](https://user-images.githubusercontent.com/7759622/33026364-50e5de62-ce21-11e7-969b-912dc6b6955b.gif)

I would love if Always Right could always preserve the default FF behavior re: opening links in bg from the same tab no matter where or how fast they were opened.

FF57, fresh profile, no other extensions/settings.

**Comment by Keith94** [comment]
Should be fixed in the latest version of Always Right if you're using Firefox Nightly.

**Comment by autonome** [comment]
The implementation and even underlying Firefox extension APIs are all different now. Please reopen if you're still seeing this!
