### ISSUE TITLE
new tabs from middle-click or context menu open to the right of other newly added tabs from that method

### ISSUE THREAD

**Issue by rayman89** [autonome/alwaysright#24]
Is this project dead? The last issue had no response and was the reason why I wanted to install this addon.

I want tab to open like before quantum ALWAYS to the right next to the current tab

Now newest tabs open the furthest away from the current tab. I always want the last tab to be the one closest to the active tab

So [Active tab] 3 2 1 instead of [Active tab] 1 2 3

Would that be possible? Otherwise I don't know what this add-on does when the preference open tabs next to current is enabled.

**Comment by autonome** [comment]
Hi @rayman89! Nope, not dead, just a side project that isn't my focus right now.

Which other issue are you're referencing? I'll see if I can take a look.

> Now newest tabs open the furthest away from the current tab. I always want the last tab to be the one closest to the active tab
> 
> So [Active tab] 3 2 1 instead of [Active tab] 1 2 3

I am not sure I understand. Can you clarify the set of steps, including the method by which you are opening the new tabs?

**Comment by rayman89** [comment]
If you are on a webpage with many links like google results page if you middle click on a link to open it the new tab (let's call it tab:A) will open right next to the results page but the second tab you open that way will open next to Tab A not next to the google results page like it used to be before they changed the addons. Is there a way to make it work like it used to be?

**Comment by rayman89** [comment]
@autonome 
![image](https://user-images.githubusercontent.com/5449042/62155414-6b9d7880-b2ce-11e9-801f-f43b8a4dc855.png)

**Comment by autonome** [comment]
Ah, ok I understand. I agree that any new tab should always open to the immediate right.

Hm, I wonder when that regression occurred.

**Comment by autonome** [comment]
Hm, maybe that is the behavior of the pref the added: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserSettings/newTabPosition

**Comment by autonome** [comment]
Confirmed, flipping back to old school method returns the desired behavior.

**Comment by autonome** [comment]
... but only tested that use-case. I'm worried that some behavior will regress if I don't flip the pref.

I wonder what would happen if I flipped the pref *and* still enabled the manual handling.

I guess I should write a test harness for all possible scenarios... but I certainly do not have time to do that right now. Still would have to manually test opening links from other applications.

**Comment by autonome** [comment]
Filed #25 for test scenarios and test harness

**Comment by rayman89** [comment]
I can test whatever you need.

**Comment by autonome** [comment]
This extension has been ported to manifest v3, works very different now. Reopen if still seeing this.
