### ISSUE TITLE
Remove `oldSchool` method to simplify?

### ISSUE THREAD

**Issue by shankari** [autonome/alwaysright#29]
`browser.browserSettings.newTabPosition` [has been supported since FF 61](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserSettings/newTabPosition). Current version is 76+.

Maybe we can remove the `oldSchool` method to simplify the extension? This also removes the need for the `tabs` permission.

I've simplified my clone of this repo and tested it in my browser. Happy to submit a PR if you think this is appropriate.

**Comment by autonome** [comment]
Thanks for filing - the code has changed and this is no longer there.

**Comment by autonome** [comment]
(and sorry for not seeing this sooner!)
