### ISSUE TITLE
Not working anymore after installing sidebery plugin

### ISSUE THREAD

**Issue by JAPMedia** [autonome/alwaysright#33]
After installing sidebery plugin, alwaysright is not working anymore.Disabling sidebery make alwaysright works again.
https://github.com/mbnuqw/sidebery/

**Comment by autonome** [comment]
Thanks, this is a known issue with Sidebery - they have it noted at the top of their readme:

https://github.com/mbnuqw/sidebery/?tab=readme-ov-file#incompatibility-with-other-addons
