### ISSUE TITLE
2.0 - New tab moves to the beginning of the visible tab bar

### ISSUE THREAD

**Issue by r-a-y** [autonome/alwaysright#8]
In the new WebExtension version, opening a new tab has the effect of moving the tab bar to the first position of the new tab.

For example, let's say tab 12 is the active tab:

| tab 10 | tab 11 | tab 12 (active) | tab 13 | tab 14... 30 |

If I open a new tab, then the tab bar becomes:

| tab 13 (new tab) | tab 14 | tab 15 | tab 16 | tab 17... 30 |

I much prefer the older XUL method of the tabbar not moving:

| tab 10 | tab 11 | tab 12 | tab 13 (new tab) | tab 14 | tab 15... 30 |

A similar addon has the same problem.  This is probably a limitation of the new WebExtension API, but thought I'd post an issue about this.

**Comment by autonome** [comment]
Whoa, thanks Ray! Which version do you have? 2.0.2? And which OS?

**Comment by r-a-y** [comment]
Using v2.0.2 on Firefox 53.  OS is Windows 10.

**Comment by dantunes** [comment]
Thanks @r-a-y for the graphical explanation. This is the issue that I was talking about on my posted issue (issue #7), plus the problem of the tab that eventually open at the far right

**Comment by autonome** [comment]
I've reverted on AMO back to 1.6.1, so you can reinstall here for a working version: https://addons.mozilla.org/en-US/firefox/addon/always-right/

**Comment by autonome** [comment]
Ancient issue, the extension and the underlying Firefox APIs are all different now. Can reopen if problem still happening!
